version: "3"

tasks:
    build:
        desc: Build the app
        cmds:
        - mkdir -vp bin
        - for folder in "linux-amd64" "linux-arm64" "darwin-amd64" "darwin-arm64"; do mkdir -pv bin/${folder}; done
        - GOOS=linux GOARCH=amd64 go build -v -o bin/linux-amd64/subnetFinder .
        - GOOS=linux GOARCH=arm64 go build -v -o bin/linux-arm64/subnetFinder .
        - GOOS=darwin GOARCH=amd64 go build -v -o bin/darwin-amd64/subnetFinder .
        - GOOS=darwin GOARCH=arm64 go build -v -o bin/darwin-arm64/subnetFinder .

    run: 
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run internal/main.go