name: deploy-identity-vm

on:
  push:
    branches:
    -  main

  workflow_dispatch:

jobs:
  create-virtual-network:
    steps:
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7
    - run: terraform init
    
    - id: plan
      run: terraform apply -auto-approve
    
  calculate-network-subnets:


  deploy-new-subnets:
