name: Build
on:
  push:
    branches:
    - main
    - dev/*
    - feature/*
    - fix/*
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
    - '**.md'
    - 'scripts/**'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '**.md'
    - 'scripts/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      - name: test
        uses: ./.github/workflows/test.yml
        with:
          go-version: 1.20
  build:
    runs-on: ubuntu-latest
    needs: ["test"]
    steps:
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.15.2

    - uses: actions/checkout@v3

    - name: Test
      run: go test -v ./...

    - run: |
        task build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: drop
        # A file, directory or wildcard pattern that describes what to upload
        path: bin
