name: build

on:
  push:
    branches:
    - main
    - dev/*
    - feature/*
    - fix/*
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
    - '**.md'
    - 'scripts/**'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '**.md'
    - 'scripts/**'

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      go-version: 1.19

  publish:
    needs: ["test"]
    uses: ./.github/workflows/publish.yml
    with:
        go-version: 1.19
        task-command: build
        artifact-name: drop
