name: Publish

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      task-command:
        description: Command  in Taskfile to use
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }} 

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.15.2

    - uses: actions/checkout@v3

    - run: |
        task ${{ inputs.task-command }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: ${{ inputs.artifact-name }}
        # A file, directory or wildcard pattern that describes what to upload
        path: bin
